server:
  port: 8080

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME:user}:${DB_PASSWORD:password}@${DB_HOST:localhost}:${DB_PORT:27017}/miniautorizador

springfox:
    enabled: true