server:
  port: 8080

spring:
  jackson:
    deserialization:
      fail-on-unknown-properties: false
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME:user}:${MONGO_INITDB_ROOT_PASSWORD:password}@${MONGODB_HOST:localhost}:27017/${MONGO_INITDB_DATABASE:miniautorizador}
#      host: ${MONGODB_HOST:localhost}
#      port: 27017
#      database: ${MONGO_INITDB_DATABASE:miniautorizador}
#      username: ${MONGO_INITDB_ROOT_USERNAME:user}
#      password: ${MONGO_INITDB_ROOT_PASSWORD:password}

#springfox:
#  documentation:
#    enabled: true