version: "3.7"

services:
  app:
    image: 'mini-autorizador:latest'
    build: ../.
#      context: .
#      dockerfile: ../Dockerfile
    container_name: mini-autorizador
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USERNAME: user
      DB_PASSWORD: password
    networks:
      - app-network

  mongo:
    image: mongo:4.2
    hostname: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: miniautorizador
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro
    networks:
      - app-network

networks:
  app-network:
    name: app-network